/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IPolicyGuardInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "check"
      | "checkView"
      | "setMaxCapETH"
      | "setUserDailyLimit"
      | "setUserWL"
      | "unsetUserWL"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "check",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkView",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxCapETH",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setUserDailyLimit",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setUserWL",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unsetUserWL",
    values: [BytesLike, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "check", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "checkView", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMaxCapETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUserDailyLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setUserWL", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unsetUserWL",
    data: BytesLike
  ): Result;
}

export interface IPolicyGuard extends BaseContract {
  connect(runner?: ContractRunner | null): IPolicyGuard;
  waitForDeployment(): Promise<this>;

  interface: IPolicyGuardInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  check: TypedContractMethod<
    [
      to: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      userKey: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;

  checkView: TypedContractMethod<
    [
      to: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      userKey: BytesLike
    ],
    [boolean],
    "view"
  >;

  setMaxCapETH: TypedContractMethod<[cap: BigNumberish], [void], "nonpayable">;

  setUserDailyLimit: TypedContractMethod<
    [userKey: BytesLike, max: BigNumberish],
    [void],
    "nonpayable"
  >;

  setUserWL: TypedContractMethod<
    [userKey: BytesLike, to: AddressLike],
    [void],
    "nonpayable"
  >;

  unsetUserWL: TypedContractMethod<
    [userKey: BytesLike, to: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "check"
  ): TypedContractMethod<
    [
      to: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      userKey: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "checkView"
  ): TypedContractMethod<
    [
      to: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      userKey: BytesLike
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "setMaxCapETH"
  ): TypedContractMethod<[cap: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setUserDailyLimit"
  ): TypedContractMethod<
    [userKey: BytesLike, max: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setUserWL"
  ): TypedContractMethod<
    [userKey: BytesLike, to: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unsetUserWL"
  ): TypedContractMethod<
    [userKey: BytesLike, to: AddressLike],
    [void],
    "nonpayable"
  >;

  filters: {};
}
