/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ColdVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptOwnership"
      | "admin1"
      | "admin2"
      | "adminDeposit"
      | "approveMove"
      | "executeMove"
      | "grantManager"
      | "isExecutableMoveView"
      | "isManager"
      | "isTss"
      | "moves"
      | "nonce"
      | "omnibusVault"
      | "owner"
      | "pause"
      | "paused"
      | "pendingOwner"
      | "renounceOwnership"
      | "requestMove"
      | "seatATss"
      | "setColdAdmins"
      | "setOmnibusVault"
      | "setTss"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ImbalanceDetected"
      | "ManagerSet"
      | "MoveApproved"
      | "MoveExecuted"
      | "MoveRequested"
      | "OwnershipTransferStarted"
      | "OwnershipTransferred"
      | "Paused"
      | "TssSet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "admin1", values?: undefined): string;
  encodeFunctionData(functionFragment: "admin2", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "adminDeposit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approveMove",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeMove",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantManager",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "isExecutableMoveView",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "isTss", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "moves", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "nonce", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "omnibusVault",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values: [boolean]): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestMove",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "seatATss", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setColdAdmins",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setOmnibusVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "setTss", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin1", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "admin2", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "adminDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveMove",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeMove",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isExecutableMoveView",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isManager", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isTss", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "moves", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nonce", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "omnibusVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestMove",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "seatATss", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setColdAdmins",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOmnibusVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setTss", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace ImbalanceDetectedEvent {
  export type InputTuple = [
    vault: AddressLike,
    omnibus: BigNumberish,
    cold: BigNumberish,
    deviationRay: BigNumberish
  ];
  export type OutputTuple = [
    vault: string,
    omnibus: bigint,
    cold: bigint,
    deviationRay: bigint
  ];
  export interface OutputObject {
    vault: string;
    omnibus: bigint;
    cold: bigint;
    deviationRay: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ManagerSetEvent {
  export type InputTuple = [manager: AddressLike, allowed: boolean];
  export type OutputTuple = [manager: string, allowed: boolean];
  export interface OutputObject {
    manager: string;
    allowed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MoveApprovedEvent {
  export type InputTuple = [moveId: BytesLike, approver: AddressLike];
  export type OutputTuple = [moveId: string, approver: string];
  export interface OutputObject {
    moveId: string;
    approver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MoveExecutedEvent {
  export type InputTuple = [moveId: BytesLike, amount: BigNumberish];
  export type OutputTuple = [moveId: string, amount: bigint];
  export interface OutputObject {
    moveId: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MoveRequestedEvent {
  export type InputTuple = [moveId: BytesLike, amount: BigNumberish];
  export type OutputTuple = [moveId: string, amount: bigint];
  export interface OutputObject {
    moveId: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [v: boolean];
  export type OutputTuple = [v: boolean];
  export interface OutputObject {
    v: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TssSetEvent {
  export type InputTuple = [tss: AddressLike];
  export type OutputTuple = [tss: string];
  export interface OutputObject {
    tss: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ColdVault extends BaseContract {
  connect(runner?: ContractRunner | null): ColdVault;
  waitForDeployment(): Promise<this>;

  interface: ColdVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  admin1: TypedContractMethod<[], [string], "view">;

  admin2: TypedContractMethod<[], [string], "view">;

  adminDeposit: TypedContractMethod<[], [void], "payable">;

  approveMove: TypedContractMethod<[moveId: BytesLike], [void], "nonpayable">;

  executeMove: TypedContractMethod<[moveId: BytesLike], [void], "nonpayable">;

  grantManager: TypedContractMethod<
    [manager: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  isExecutableMoveView: TypedContractMethod<
    [moveId: BytesLike],
    [boolean],
    "view"
  >;

  isManager: TypedContractMethod<[a: AddressLike], [boolean], "view">;

  isTss: TypedContractMethod<[a: AddressLike], [boolean], "view">;

  moves: TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, boolean, boolean, boolean, string, string] & {
        amount: bigint;
        approvedAdmin1: boolean;
        approvedAdmin2: boolean;
        executed: boolean;
        approver1: string;
        approver2: string;
      }
    ],
    "view"
  >;

  nonce: TypedContractMethod<[], [bigint], "view">;

  omnibusVault: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[v: boolean], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requestMove: TypedContractMethod<
    [amount: BigNumberish],
    [string],
    "nonpayable"
  >;

  seatATss: TypedContractMethod<[], [string], "view">;

  setColdAdmins: TypedContractMethod<
    [_a1: AddressLike, _a2: AddressLike],
    [void],
    "nonpayable"
  >;

  setOmnibusVault: TypedContractMethod<[v: AddressLike], [void], "nonpayable">;

  setTss: TypedContractMethod<[tss: AddressLike], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "admin1"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "admin2"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "adminDeposit"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "approveMove"
  ): TypedContractMethod<[moveId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeMove"
  ): TypedContractMethod<[moveId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "grantManager"
  ): TypedContractMethod<
    [manager: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isExecutableMoveView"
  ): TypedContractMethod<[moveId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isManager"
  ): TypedContractMethod<[a: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isTss"
  ): TypedContractMethod<[a: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "moves"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, boolean, boolean, boolean, string, string] & {
        amount: bigint;
        approvedAdmin1: boolean;
        approvedAdmin2: boolean;
        executed: boolean;
        approver1: string;
        approver2: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "nonce"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "omnibusVault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[v: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestMove"
  ): TypedContractMethod<[amount: BigNumberish], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "seatATss"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setColdAdmins"
  ): TypedContractMethod<
    [_a1: AddressLike, _a2: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setOmnibusVault"
  ): TypedContractMethod<[v: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTss"
  ): TypedContractMethod<[tss: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ImbalanceDetected"
  ): TypedContractEvent<
    ImbalanceDetectedEvent.InputTuple,
    ImbalanceDetectedEvent.OutputTuple,
    ImbalanceDetectedEvent.OutputObject
  >;
  getEvent(
    key: "ManagerSet"
  ): TypedContractEvent<
    ManagerSetEvent.InputTuple,
    ManagerSetEvent.OutputTuple,
    ManagerSetEvent.OutputObject
  >;
  getEvent(
    key: "MoveApproved"
  ): TypedContractEvent<
    MoveApprovedEvent.InputTuple,
    MoveApprovedEvent.OutputTuple,
    MoveApprovedEvent.OutputObject
  >;
  getEvent(
    key: "MoveExecuted"
  ): TypedContractEvent<
    MoveExecutedEvent.InputTuple,
    MoveExecutedEvent.OutputTuple,
    MoveExecutedEvent.OutputObject
  >;
  getEvent(
    key: "MoveRequested"
  ): TypedContractEvent<
    MoveRequestedEvent.InputTuple,
    MoveRequestedEvent.OutputTuple,
    MoveRequestedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "TssSet"
  ): TypedContractEvent<
    TssSetEvent.InputTuple,
    TssSetEvent.OutputTuple,
    TssSetEvent.OutputObject
  >;

  filters: {
    "ImbalanceDetected(address,uint256,uint256,uint256)": TypedContractEvent<
      ImbalanceDetectedEvent.InputTuple,
      ImbalanceDetectedEvent.OutputTuple,
      ImbalanceDetectedEvent.OutputObject
    >;
    ImbalanceDetected: TypedContractEvent<
      ImbalanceDetectedEvent.InputTuple,
      ImbalanceDetectedEvent.OutputTuple,
      ImbalanceDetectedEvent.OutputObject
    >;

    "ManagerSet(address,bool)": TypedContractEvent<
      ManagerSetEvent.InputTuple,
      ManagerSetEvent.OutputTuple,
      ManagerSetEvent.OutputObject
    >;
    ManagerSet: TypedContractEvent<
      ManagerSetEvent.InputTuple,
      ManagerSetEvent.OutputTuple,
      ManagerSetEvent.OutputObject
    >;

    "MoveApproved(bytes32,address)": TypedContractEvent<
      MoveApprovedEvent.InputTuple,
      MoveApprovedEvent.OutputTuple,
      MoveApprovedEvent.OutputObject
    >;
    MoveApproved: TypedContractEvent<
      MoveApprovedEvent.InputTuple,
      MoveApprovedEvent.OutputTuple,
      MoveApprovedEvent.OutputObject
    >;

    "MoveExecuted(bytes32,uint256)": TypedContractEvent<
      MoveExecutedEvent.InputTuple,
      MoveExecutedEvent.OutputTuple,
      MoveExecutedEvent.OutputObject
    >;
    MoveExecuted: TypedContractEvent<
      MoveExecutedEvent.InputTuple,
      MoveExecutedEvent.OutputTuple,
      MoveExecutedEvent.OutputObject
    >;

    "MoveRequested(bytes32,uint256)": TypedContractEvent<
      MoveRequestedEvent.InputTuple,
      MoveRequestedEvent.OutputTuple,
      MoveRequestedEvent.OutputObject
    >;
    MoveRequested: TypedContractEvent<
      MoveRequestedEvent.InputTuple,
      MoveRequestedEvent.OutputTuple,
      MoveRequestedEvent.OutputObject
    >;

    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(bool)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "TssSet(address)": TypedContractEvent<
      TssSetEvent.InputTuple,
      TssSetEvent.OutputTuple,
      TssSetEvent.OutputObject
    >;
    TssSet: TypedContractEvent<
      TssSetEvent.InputTuple,
      TssSetEvent.OutputTuple,
      TssSetEvent.OutputObject
    >;
  };
}
