/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as base from "./base";
export type { base };
export type { ColdVault } from "./ColdVault";
export type { OmnibusVault } from "./OmnibusVault";
export type { PolicyGuard } from "./PolicyGuard";
