/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as coldVaultV2Sol from "./ColdVaultV2.sol";
export type { coldVaultV2Sol };
import type * as base from "./base";
export type { base };
export type { ColdVault } from "./ColdVault";
export type { MerkleAnchor } from "./MerkleAnchor";
export type { OmnibusVaultV2 } from "./OmnibusVaultV2";
export type { PolicyGuard } from "./PolicyGuard";
