/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface OmnibusVaultV2Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptOwnership"
      | "approveTx"
      | "coldVault"
      | "computeTxId"
      | "depositETH"
      | "execute"
      | "grantManager"
      | "isManager"
      | "isTss"
      | "nonce"
      | "owner"
      | "pause"
      | "paused"
      | "pendingOwner"
      | "policyGuard"
      | "renounceOwnership"
      | "seatATss"
      | "setColdVault"
      | "setPolicyGuard"
      | "setTss"
      | "submitTx"
      | "transferOwnership"
      | "txs"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Approved"
      | "Deposit"
      | "Executed"
      | "ManagerSet"
      | "OwnershipTransferStarted"
      | "OwnershipTransferred"
      | "Paused"
      | "Submitted"
      | "TssSet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approveTx",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "coldVault", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "computeTxId",
    values: [AddressLike, BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositETH",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "execute",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grantManager",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "isManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "isTss", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "nonce", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values: [boolean]): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "policyGuard",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "seatATss", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setColdVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPolicyGuard",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "setTss", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "submitTx",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "txs", values: [BytesLike]): string;

  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "approveTx", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "coldVault", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "computeTxId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "depositETH", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "grantManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isManager", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isTss", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nonce", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "policyGuard",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "seatATss", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setColdVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPolicyGuard",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setTss", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "submitTx", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "txs", data: BytesLike): Result;
}

export namespace ApprovedEvent {
  export type InputTuple = [txId: BytesLike, approver: AddressLike];
  export type OutputTuple = [txId: string, approver: string];
  export interface OutputObject {
    txId: string;
    approver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositEvent {
  export type InputTuple = [
    userKey: BytesLike,
    from: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    userKey: string,
    from: string,
    token: string,
    amount: bigint
  ];
  export interface OutputObject {
    userKey: string;
    from: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutedEvent {
  export type InputTuple = [txId: BytesLike];
  export type OutputTuple = [txId: string];
  export interface OutputObject {
    txId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ManagerSetEvent {
  export type InputTuple = [manager: AddressLike, allowed: boolean];
  export type OutputTuple = [manager: string, allowed: boolean];
  export interface OutputObject {
    manager: string;
    allowed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [v: boolean];
  export type OutputTuple = [v: boolean];
  export interface OutputObject {
    v: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubmittedEvent {
  export type InputTuple = [
    txId: BytesLike,
    to: AddressLike,
    amount: BigNumberish,
    userKey: BytesLike
  ];
  export type OutputTuple = [
    txId: string,
    to: string,
    amount: bigint,
    userKey: string
  ];
  export interface OutputObject {
    txId: string;
    to: string;
    amount: bigint;
    userKey: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TssSetEvent {
  export type InputTuple = [tss: AddressLike];
  export type OutputTuple = [tss: string];
  export interface OutputObject {
    tss: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface OmnibusVaultV2 extends BaseContract {
  connect(runner?: ContractRunner | null): OmnibusVaultV2;
  waitForDeployment(): Promise<this>;

  interface: OmnibusVaultV2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  approveTx: TypedContractMethod<[txId: BytesLike], [void], "nonpayable">;

  coldVault: TypedContractMethod<[], [string], "view">;

  computeTxId: TypedContractMethod<
    [
      to: AddressLike,
      amount: BigNumberish,
      userKey: BytesLike,
      _nonce: BigNumberish
    ],
    [string],
    "view"
  >;

  depositETH: TypedContractMethod<[userKey: BytesLike], [void], "payable">;

  execute: TypedContractMethod<
    [txId: BytesLike, smallTxThresholdWei: BigNumberish],
    [void],
    "nonpayable"
  >;

  grantManager: TypedContractMethod<
    [manager: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  isManager: TypedContractMethod<[a: AddressLike], [boolean], "view">;

  isTss: TypedContractMethod<[a: AddressLike], [boolean], "view">;

  nonce: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[v: boolean], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  policyGuard: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  seatATss: TypedContractMethod<[], [string], "view">;

  setColdVault: TypedContractMethod<[v: AddressLike], [void], "nonpayable">;

  setPolicyGuard: TypedContractMethod<[_p: AddressLike], [void], "nonpayable">;

  setTss: TypedContractMethod<[tss: AddressLike], [void], "nonpayable">;

  submitTx: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish, userKey: BytesLike],
    [string],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  txs: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, string, boolean, boolean, boolean] & {
        to: string;
        amount: bigint;
        userKey: string;
        approvedTss: boolean;
        approvedManager: boolean;
        executed: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "approveTx"
  ): TypedContractMethod<[txId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "coldVault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "computeTxId"
  ): TypedContractMethod<
    [
      to: AddressLike,
      amount: BigNumberish,
      userKey: BytesLike,
      _nonce: BigNumberish
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "depositETH"
  ): TypedContractMethod<[userKey: BytesLike], [void], "payable">;
  getFunction(
    nameOrSignature: "execute"
  ): TypedContractMethod<
    [txId: BytesLike, smallTxThresholdWei: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "grantManager"
  ): TypedContractMethod<
    [manager: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isManager"
  ): TypedContractMethod<[a: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isTss"
  ): TypedContractMethod<[a: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "nonce"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[v: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "policyGuard"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "seatATss"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setColdVault"
  ): TypedContractMethod<[v: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPolicyGuard"
  ): TypedContractMethod<[_p: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTss"
  ): TypedContractMethod<[tss: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitTx"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish, userKey: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "txs"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, string, boolean, boolean, boolean] & {
        to: string;
        amount: bigint;
        userKey: string;
        approvedTss: boolean;
        approvedManager: boolean;
        executed: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "Approved"
  ): TypedContractEvent<
    ApprovedEvent.InputTuple,
    ApprovedEvent.OutputTuple,
    ApprovedEvent.OutputObject
  >;
  getEvent(
    key: "Deposit"
  ): TypedContractEvent<
    DepositEvent.InputTuple,
    DepositEvent.OutputTuple,
    DepositEvent.OutputObject
  >;
  getEvent(
    key: "Executed"
  ): TypedContractEvent<
    ExecutedEvent.InputTuple,
    ExecutedEvent.OutputTuple,
    ExecutedEvent.OutputObject
  >;
  getEvent(
    key: "ManagerSet"
  ): TypedContractEvent<
    ManagerSetEvent.InputTuple,
    ManagerSetEvent.OutputTuple,
    ManagerSetEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "Submitted"
  ): TypedContractEvent<
    SubmittedEvent.InputTuple,
    SubmittedEvent.OutputTuple,
    SubmittedEvent.OutputObject
  >;
  getEvent(
    key: "TssSet"
  ): TypedContractEvent<
    TssSetEvent.InputTuple,
    TssSetEvent.OutputTuple,
    TssSetEvent.OutputObject
  >;

  filters: {
    "Approved(bytes32,address)": TypedContractEvent<
      ApprovedEvent.InputTuple,
      ApprovedEvent.OutputTuple,
      ApprovedEvent.OutputObject
    >;
    Approved: TypedContractEvent<
      ApprovedEvent.InputTuple,
      ApprovedEvent.OutputTuple,
      ApprovedEvent.OutputObject
    >;

    "Deposit(bytes32,address,address,uint256)": TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;
    Deposit: TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;

    "Executed(bytes32)": TypedContractEvent<
      ExecutedEvent.InputTuple,
      ExecutedEvent.OutputTuple,
      ExecutedEvent.OutputObject
    >;
    Executed: TypedContractEvent<
      ExecutedEvent.InputTuple,
      ExecutedEvent.OutputTuple,
      ExecutedEvent.OutputObject
    >;

    "ManagerSet(address,bool)": TypedContractEvent<
      ManagerSetEvent.InputTuple,
      ManagerSetEvent.OutputTuple,
      ManagerSetEvent.OutputObject
    >;
    ManagerSet: TypedContractEvent<
      ManagerSetEvent.InputTuple,
      ManagerSetEvent.OutputTuple,
      ManagerSetEvent.OutputObject
    >;

    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(bool)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "Submitted(bytes32,address,uint256,bytes32)": TypedContractEvent<
      SubmittedEvent.InputTuple,
      SubmittedEvent.OutputTuple,
      SubmittedEvent.OutputObject
    >;
    Submitted: TypedContractEvent<
      SubmittedEvent.InputTuple,
      SubmittedEvent.OutputTuple,
      SubmittedEvent.OutputObject
    >;

    "TssSet(address)": TypedContractEvent<
      TssSetEvent.InputTuple,
      TssSetEvent.OutputTuple,
      TssSetEvent.OutputObject
    >;
    TssSet: TypedContractEvent<
      TssSetEvent.InputTuple,
      TssSetEvent.OutputTuple,
      TssSetEvent.OutputObject
    >;
  };
}
