/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface PolicyGuardInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "check"
      | "checkView"
      | "maxCapETH"
      | "owner"
      | "renounceOwnership"
      | "setMaxCapETH"
      | "setUserDailyLimit"
      | "setUserWL"
      | "transferOwnership"
      | "unsetUserWL"
      | "userDailyETH"
      | "userWL"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MaxCapUpdated"
      | "OwnershipTransferred"
      | "UserDailyLimitUpdated"
      | "UserWLUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "check",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkView",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "maxCapETH", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxCapETH",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setUserDailyLimit",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setUserWL",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unsetUserWL",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userDailyETH",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userWL",
    values: [BytesLike, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "check", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "checkView", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "maxCapETH", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxCapETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUserDailyLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setUserWL", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unsetUserWL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userDailyETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userWL", data: BytesLike): Result;
}

export namespace MaxCapUpdatedEvent {
  export type InputTuple = [cap: BigNumberish];
  export type OutputTuple = [cap: bigint];
  export interface OutputObject {
    cap: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserDailyLimitUpdatedEvent {
  export type InputTuple = [userKey: BytesLike, max: BigNumberish];
  export type OutputTuple = [userKey: string, max: bigint];
  export interface OutputObject {
    userKey: string;
    max: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserWLUpdatedEvent {
  export type InputTuple = [
    userKey: BytesLike,
    to: AddressLike,
    allowed: boolean
  ];
  export type OutputTuple = [userKey: string, to: string, allowed: boolean];
  export interface OutputObject {
    userKey: string;
    to: string;
    allowed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PolicyGuard extends BaseContract {
  connect(runner?: ContractRunner | null): PolicyGuard;
  waitForDeployment(): Promise<this>;

  interface: PolicyGuardInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  check: TypedContractMethod<
    [
      to: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      userKey: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;

  checkView: TypedContractMethod<
    [
      to: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      userKey: BytesLike
    ],
    [boolean],
    "view"
  >;

  maxCapETH: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setMaxCapETH: TypedContractMethod<[cap: BigNumberish], [void], "nonpayable">;

  setUserDailyLimit: TypedContractMethod<
    [userKey: BytesLike, max: BigNumberish],
    [void],
    "nonpayable"
  >;

  setUserWL: TypedContractMethod<
    [userKey: BytesLike, to: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unsetUserWL: TypedContractMethod<
    [userKey: BytesLike, to: AddressLike],
    [void],
    "nonpayable"
  >;

  userDailyETH: TypedContractMethod<
    [arg0: BytesLike],
    [[bigint, bigint, bigint] & { max: bigint; spent: bigint; dayKey: bigint }],
    "view"
  >;

  userWL: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "check"
  ): TypedContractMethod<
    [
      to: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      userKey: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "checkView"
  ): TypedContractMethod<
    [
      to: AddressLike,
      token: AddressLike,
      amount: BigNumberish,
      userKey: BytesLike
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "maxCapETH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMaxCapETH"
  ): TypedContractMethod<[cap: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setUserDailyLimit"
  ): TypedContractMethod<
    [userKey: BytesLike, max: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setUserWL"
  ): TypedContractMethod<
    [userKey: BytesLike, to: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unsetUserWL"
  ): TypedContractMethod<
    [userKey: BytesLike, to: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userDailyETH"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [[bigint, bigint, bigint] & { max: bigint; spent: bigint; dayKey: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "userWL"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  getEvent(
    key: "MaxCapUpdated"
  ): TypedContractEvent<
    MaxCapUpdatedEvent.InputTuple,
    MaxCapUpdatedEvent.OutputTuple,
    MaxCapUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "UserDailyLimitUpdated"
  ): TypedContractEvent<
    UserDailyLimitUpdatedEvent.InputTuple,
    UserDailyLimitUpdatedEvent.OutputTuple,
    UserDailyLimitUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "UserWLUpdated"
  ): TypedContractEvent<
    UserWLUpdatedEvent.InputTuple,
    UserWLUpdatedEvent.OutputTuple,
    UserWLUpdatedEvent.OutputObject
  >;

  filters: {
    "MaxCapUpdated(uint256)": TypedContractEvent<
      MaxCapUpdatedEvent.InputTuple,
      MaxCapUpdatedEvent.OutputTuple,
      MaxCapUpdatedEvent.OutputObject
    >;
    MaxCapUpdated: TypedContractEvent<
      MaxCapUpdatedEvent.InputTuple,
      MaxCapUpdatedEvent.OutputTuple,
      MaxCapUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "UserDailyLimitUpdated(bytes32,uint256)": TypedContractEvent<
      UserDailyLimitUpdatedEvent.InputTuple,
      UserDailyLimitUpdatedEvent.OutputTuple,
      UserDailyLimitUpdatedEvent.OutputObject
    >;
    UserDailyLimitUpdated: TypedContractEvent<
      UserDailyLimitUpdatedEvent.InputTuple,
      UserDailyLimitUpdatedEvent.OutputTuple,
      UserDailyLimitUpdatedEvent.OutputObject
    >;

    "UserWLUpdated(bytes32,address,bool)": TypedContractEvent<
      UserWLUpdatedEvent.InputTuple,
      UserWLUpdatedEvent.OutputTuple,
      UserWLUpdatedEvent.OutputObject
    >;
    UserWLUpdated: TypedContractEvent<
      UserWLUpdatedEvent.InputTuple,
      UserWLUpdatedEvent.OutputTuple,
      UserWLUpdatedEvent.OutputObject
    >;
  };
}
