/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  MockReceiverReverts,
  MockReceiverRevertsInterface,
} from "../../../contracts/test-helpers/MockReceiverReverts";

const _abi = [
  {
    stateMutability: "payable",
    type: "fallback",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b5060a780601d6000396000f3fe60806040523660415760405162461bcd60e51b81526004016038906020808252600490820152634e4f504560e01b604082015260600190565b60405180910390fd5b60405162461bcd60e51b81526004016038906020808252600490820152634e4f504560e01b60408201526060019056fea26469706673582212200992a3bf2f35cff930dc974df3c7bbb986e2d0883df19ee38d36dd1b8543627064736f6c634300081a0033";

type MockReceiverRevertsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockReceiverRevertsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockReceiverReverts__factory extends ContractFactory {
  constructor(...args: MockReceiverRevertsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockReceiverReverts & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): MockReceiverReverts__factory {
    return super.connect(runner) as MockReceiverReverts__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockReceiverRevertsInterface {
    return new Interface(_abi) as MockReceiverRevertsInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockReceiverReverts {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as MockReceiverReverts;
  }
}
