/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as coldVaultV2Sol from "./ColdVaultV2.sol";
export * as base from "./base";
export { ColdVault__factory } from "./ColdVault__factory";
export { MerkleAnchor__factory } from "./MerkleAnchor__factory";
export { OmnibusVaultV2__factory } from "./OmnibusVaultV2__factory";
export { PolicyGuard__factory } from "./PolicyGuard__factory";
