/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPolicyGuard,
  IPolicyGuardInterface,
} from "../../../contracts/interfaces/IPolicyGuard";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "userKey",
        type: "bytes32",
      },
    ],
    name: "check",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "userKey",
        type: "bytes32",
      },
    ],
    name: "checkView",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "cap",
        type: "uint256",
      },
    ],
    name: "setMaxCapETH",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "userKey",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "max",
        type: "uint256",
      },
    ],
    name: "setUserDailyLimit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "userKey",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "setUserWL",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "userKey",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "unsetUserWL",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPolicyGuard__factory {
  static readonly abi = _abi;
  static createInterface(): IPolicyGuardInterface {
    return new Interface(_abi) as IPolicyGuardInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPolicyGuard {
    return new Contract(address, _abi, runner) as unknown as IPolicyGuard;
  }
}
