/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "AccessControl",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AccessControl__factory>;
    getContractFactory(
      name: "IAccessControl",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAccessControl__factory>;
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "Ownable2Step",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable2Step__factory>;
    getContractFactory(
      name: "MerkleProof",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MerkleProof__factory>;
    getContractFactory(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC165__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "AdminManagerBase",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AdminManagerBase__factory>;
    getContractFactory(
      name: "AdminSeats",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AdminSeats__factory>;
    getContractFactory(
      name: "ColdVault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ColdVault__factory>;
    getContractFactory(
      name: "MerkleAnchor",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MerkleAnchor__factory>;
    getContractFactory(
      name: "OmnibusVault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OmnibusVault__factory>;
    getContractFactory(
      name: "PolicyGuard",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PolicyGuard__factory>;
    getContractFactory(
      name: "IPolicyGuard",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPolicyGuard__factory>;
    getContractFactory(
      name: "ForceSend",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ForceSend__factory>;
    getContractFactory(
      name: "MockReceiverReverts",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockReceiverReverts__factory>;

    getContractAt(
      name: "AccessControl",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AccessControl>;
    getContractAt(
      name: "IAccessControl",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAccessControl>;
    getContractAt(
      name: "Ownable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "Ownable2Step",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable2Step>;
    getContractAt(
      name: "MerkleProof",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MerkleProof>;
    getContractAt(
      name: "ERC165",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC165>;
    getContractAt(
      name: "IERC165",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "AdminManagerBase",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AdminManagerBase>;
    getContractAt(
      name: "AdminSeats",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AdminSeats>;
    getContractAt(
      name: "ColdVault",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ColdVault>;
    getContractAt(
      name: "MerkleAnchor",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MerkleAnchor>;
    getContractAt(
      name: "OmnibusVault",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.OmnibusVault>;
    getContractAt(
      name: "PolicyGuard",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PolicyGuard>;
    getContractAt(
      name: "IPolicyGuard",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPolicyGuard>;
    getContractAt(
      name: "ForceSend",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ForceSend>;
    getContractAt(
      name: "MockReceiverReverts",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockReceiverReverts>;

    deployContract(
      name: "AccessControl",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AccessControl>;
    deployContract(
      name: "IAccessControl",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAccessControl>;
    deployContract(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "Ownable2Step",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable2Step>;
    deployContract(
      name: "MerkleProof",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MerkleProof>;
    deployContract(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC165>;
    deployContract(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "AdminManagerBase",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AdminManagerBase>;
    deployContract(
      name: "AdminSeats",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AdminSeats>;
    deployContract(
      name: "ColdVault",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ColdVault>;
    deployContract(
      name: "MerkleAnchor",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MerkleAnchor>;
    deployContract(
      name: "OmnibusVault",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.OmnibusVault>;
    deployContract(
      name: "PolicyGuard",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PolicyGuard>;
    deployContract(
      name: "IPolicyGuard",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPolicyGuard>;
    deployContract(
      name: "ForceSend",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ForceSend>;
    deployContract(
      name: "MockReceiverReverts",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockReceiverReverts>;

    deployContract(
      name: "AccessControl",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AccessControl>;
    deployContract(
      name: "IAccessControl",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAccessControl>;
    deployContract(
      name: "Ownable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "Ownable2Step",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable2Step>;
    deployContract(
      name: "MerkleProof",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MerkleProof>;
    deployContract(
      name: "ERC165",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC165>;
    deployContract(
      name: "IERC165",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "AdminManagerBase",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AdminManagerBase>;
    deployContract(
      name: "AdminSeats",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AdminSeats>;
    deployContract(
      name: "ColdVault",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ColdVault>;
    deployContract(
      name: "MerkleAnchor",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MerkleAnchor>;
    deployContract(
      name: "OmnibusVault",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.OmnibusVault>;
    deployContract(
      name: "PolicyGuard",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PolicyGuard>;
    deployContract(
      name: "IPolicyGuard",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPolicyGuard>;
    deployContract(
      name: "ForceSend",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ForceSend>;
    deployContract(
      name: "MockReceiverReverts",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockReceiverReverts>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
